# Node.js 18 버전을 기반 이미지로 사용
FROM node:18-alpine

# 앱 디렉터리 생성
WORKDIR /user/src/app

# 앱 의존성 설치
COPY package*.json ./
RUN npm install -g npm@latest
RUN npm install

# 앱 소스 추가
COPY . .

# 앱 빌드
RUN npm run build

# 서버가 3000번 포트에서 실행되므로 Docker에서도 이 포트를 열어준다는뜻
EXPOSE 3000

# 앱 실행 명령어
CMD [ "npm", "run", "start" ]