pipeline {
    agent any
    environment {
        DOCKER = 'sudo docker'
    }

    stages {
        stage('Check directory') {
            steps {
                sh 'ls -al'
            }
        }

        stage('Clone Repository') {
            steps {
                checkout scm
                echo 'Checkout Scm'
            }
        }

        stage('Build image') {
            steps {
                dir('FE') {
                    sh 'ls -al'
                    sh 'docker login -u godseye93 -p wjdtmfgh123'
                    sh 'docker build -t godseye93/front:latest .'
                }
                echo 'Build image...'
            }
        }

        stage('Remove Previous image') {
            steps {
                script {
                    try {
                        sh 'docker stop front'
                        sh 'docker rm front'
                    } catch (e) {
                        echo 'fail to stop and remove container'
                    }
                }
            }
        }

        stage('Run New image') {
            steps {
                sh 'docker run --name front -d -p 3000:3000 godseye93/front:latest'
                echo 'Run New member image'
            }
        }
    }
}
