pipeline {
    agent any
    environment {
        DOCKER = 'sudo docker'
    }

    stages {
        stage('Check directory') {
            steps {
                sh 'ls -al'
                script {
                    def commitAuthor = sh(script: 'git log -1 --pretty=%an', returnStdout: true).trim()
                    env.COMMIT_AUTHOR = commitAuthor

                    def commitMessage = sh(script: 'git log -1 --pretty=%B', returnStdout: true).trim()
                    env.COMMIT_MESSAGE = commitMessage
                }
            }
        }

        stage('Clone Repository') {
            steps {
                mattermostSend color: 'warning', message: ":angry_jenkins_face: 배포 시작! :angry_jenkins_face: \n`front - #${env.BUILD_NUMBER}`\nStarted by GitLab push by ${env.COMMIT_AUTHOR}\n링크: ${env.BUILD_URL}"
                checkout scm
                echo 'Checkout Scm'
            }
        }

        stage('Build image') {
            steps {
                dir('FE') {
                    sh 'ls -al'
                    sh 'docker login -u godseye93 -p wjdtmfgh123'
                    sh 'docker build -t godseye93/front:latest .'
                }
                echo 'Build image...'
            }
        }

        stage('Remove Previous image') {
            steps {
                script {
                    try {
                        sh 'docker stop front'
                        sh 'docker rm front'
                    } catch (e) {
                        echo 'fail to stop and remove container'
                    }
                }
            }
        }

        stage('Run New image') {
            steps {
                sh 'docker run --name front -d -p 3000:3000 godseye93/front:latest'
                echo 'Run New member image'
            }
        }
    }
    post {
        success {
            mattermostSend color: 'good', message: ":jampepebyyeah: 배포 완료! :jampepebyyeah: \n`front - #${env.BUILD_NUMBER}`\nStarted by changes from ${env.COMMIT_AUTHOR}\n**${env.COMMIT_MESSAGE}** \n링크: ${env.BUILD_URL}"
        }
        failure {
            mattermostSend color: 'danger', message: ":angry_pepe_2: 배포 실패! :angry_pepe_2: \n:angry_pepe_2: :angry_pepe_2: :angry_pepe_2: :angry_pepe_2: :angry_pepe_2: \n:angry_pepe_2: :angry_pepe_2: :angry_pepe_2: :angry_pepe_2: :angry_pepe_2:"
        }
    }

}
