pipeline {
    agent any
    environment {
        DOCKER = 'sudo docker'
    }

    stages {
        stage('Check directory') {
            steps {
                sh 'ls -al'
            }
        }

        stage('Clone Repository') {
            steps {
                checkout scm
                echo 'Checkout Scm'
            }
        }

        stage('Build image') {
            steps {
                dir('troubleShooting') {
                    sh 'ls -al'
                    sh 'chmod +x ./gradlew'
                    sh './gradlew build'
                    sh 'docker login -u godseye93 -p wjdtmfgh123'
                    sh 'docker build -t godseye93/troubleShooting:latest .'
                }
                echo 'Build image...'
            }
        }

        stage('Remove Previous image') {
            steps {
                script {
                    try {
                        sh 'docker stop troubleShooting'
                        sh 'docker rm troubleShooting'
                    } catch (e) {
                        echo 'fail to stop and remove container'
                    }
                }
            }
        }
        stage('Run New image') {
            steps {
                sh 'docker run --name troubleShooting -d -p 8104:8104 godseye93/troubleShooting:latest'
                echo 'Run New member image'
            }
        }
    }
}